package lesson7;

import javax.swing.*;
import java.awt.*;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

public class StringUtility extends JFrame {
    private JPanel panelMain;
    private JTextField input;
    private JTextField output;
    private JButton countLettersButton;
    private JButton reverseLettersButton;
    private JButton removeDuplicatesButton;
    private JLabel inputLabel;
    private JLabel outputLabel;

    public StringUtility() {
        reverseLettersButton.addActionListener(e -> {
            if (input.getText() == null) output.setText("");
            else
                output.setText(new StringBuilder(input.getText()).reverse().toString());

        });
        countLettersButton.addActionListener(e -> {
            if (input.getText() == null) output.setText("");
            else output.setText(String.valueOf(input.getText().length()));

        });
        removeDuplicatesButton.addActionListener(e -> {
            if (input.getText() == null) {
                output.setText("");
            } else {
                char[] characters = input.getText().toLowerCase(Locale.ROOT).toCharArray();
                Set<Character> set = new HashSet<>();
                StringBuilder sb = new StringBuilder();
                for (char c : characters)
                    if (!set.contains(c)) {
                        set.add(c);
                        sb.append(c);
                    }
                output.setText(sb.toString());
            }
        });
    }

    public static void main(String[] args) {
        StringUtility m = new StringUtility();
        m.setContentPane(m.panelMain);
        m.setVisible(true);
        m.setSize(500, 200);
        m.setTitle("String Utility");
        m.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelMain = new JPanel();
        panelMain.setLayout(new GridBagLayout());
        output = new JTextField();
        output.setColumns(0);
        output.setForeground(new Color(-6243425));
        output.setPreferredSize(new Dimension(250, 30));
        output.setText("");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelMain.add(output, gbc);
        countLettersButton = new JButton();
        countLettersButton.setText("Count Letters        ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panelMain.add(countLettersButton, gbc);
        reverseLettersButton = new JButton();
        reverseLettersButton.setText("Reverse Letters     ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panelMain.add(reverseLettersButton, gbc);
        removeDuplicatesButton = new JButton();
        removeDuplicatesButton.setText("Remove Duplicates");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        panelMain.add(removeDuplicatesButton, gbc);
        input = new JTextField();
        input.setPreferredSize(new Dimension(250, 30));
        input.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelMain.add(input, gbc);
        inputLabel = new JLabel();
        inputLabel.setAlignmentY(0.0f);
        inputLabel.setText("input");
        inputLabel.setVerticalAlignment(1);
        inputLabel.setVerticalTextPosition(1);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelMain.add(inputLabel, gbc);
        outputLabel = new JLabel();
        outputLabel.setText("output");
        outputLabel.setVerticalAlignment(3);
        outputLabel.setVerticalTextPosition(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panelMain.add(outputLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelMain;
    }

}
